# Generated by Django 2.2.10 on 2021-09-17 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('Account_Id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mall_account', to='digeiz.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('Mall_Id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit_mall', to='digeiz.Mall')),
            ],
        ),
    ]
